[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@aws-sdk/*", "openai"]
  included_files = ["app/**", "components/**", "lib/**"]
  directory = "netlify/functions"

[dev]
  framework = "next"

[context.production.environment]
  NEXT_TELEMETRY_DISABLED = "1"

# Remember to set the following env vars in Netlify UI:
# AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_S3_BUCKET, AWS_S3_REGION
# OPENAI_API_KEY
# Enable Netlify Identity for Admin. Netlify Blobs must be enabled on the site.
